apiVersion: apps/v1
kind: Deployment
metadata:
  name: azsh-dind
  labels:
    app: azsh-dind-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azsh-dind-agent
  template:
    metadata:
      labels:
        app: azsh-dind-agent
    spec:
      volumes:
        - name: docker-tls-certdir
          emptyDir: {}
      containers:
      - name: docker-cli
        image: dheerajlearningdocker/ado-k8s-agent:latest
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
          - name: docker-tls-certdir
            mountPath: /certs
      - name: docker-daemon
        image: docker:dind
        command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
        securityContext:
          privileged: true
        env:
          - name: DOCKER_TLS_CERTDIR
            value: tcp://localhost:2375
        volumeMounts:
         - name: docker-tls-certdir
           mountPath: /certs