apiVersion: apps/v1
kind: Deployment
metadata:
  name: azsh-dind
  labels:
    app: azsh-dind-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azsh-dind-agent
  template:
    metadata:
      labels:
        app: azsh-dind-agent
      # annotations:
      #   io.kubernetes.cri-o.userns-mode: "auto:size=65536"
    spec:
      # runtimeClassName: sysbox-runc
      containers:
      - name: dind
        image: dheerajlearningdocker/ado-k8s-agent:v1
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL