apiVersion: apps/v1
kind: Deployment
metadata:
  name: ado-agents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ado-agents
  template:
    metadata:
      labels:
        app: ado-agents
    spec:
      # volumes:
      #   - name: docker-tls-certdir
      #     emptyDir: {}
      serviceAccountName: ado
      containers:
      - name: ado
        image: dheerajlearningdocker/ado-k8s-agent:latest
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          # - name: DOCKER_TLS_CERTDIR
          #   value: /certs
          - name: AZP_URL
            value: ""
          - name: AZP_TOKEN
            value: ""
            value: linux-agent
        # volumeMounts:
        #   - name: docker-tls-certdir
        #     mountPath: /certs
      - name: docker
        image: docker:dind
        command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
        securityContext:
          privileged: true
        env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
        # volumeMounts:
        #  - name: docker-tls-certdir
        #    mountPath: /certs