apiVersion: v1
kind: ServiceAccount
metadata:
  name: ado
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ado
  namespace: default
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ado
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ado
subjects:
- kind: ServiceAccount
  name: ado
  namespace: default